name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: nuget restore SharpExt4.sln

      - name: Build solution
        run: msbuild SharpExt4.sln /p:Configuration=Release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Release for version ${{ github.ref_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
